spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/hoaxify
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  profiles:
    active:
      - production
      - dev
hoaxify:
  upload-path: picture-storage
---
spring:
  profiles: production
hoaxify:
  upload-path: storage-production
---
spring:
  profiles: dev
hoaxify:
  upload-path: storage-dev
